const views={home:document.querySelector('#homeView'),analyze:document.querySelector('#analyzeView'),electricity:document.querySelector('#electricityView'),watch:document.querySelector('#watchView')};function showView(name){Object.entries(views).forEach(([key,el])=>el.classList.toggle('active',key===name));window.scrollTo({top:0,behavior:'smooth'});document.querySelectorAll('[data-view]').forEach(btn=>btn.classList.toggle('is-active',btn.dataset.view===name))}document.querySelectorAll('[data-view]').forEach(btn=>btn.addEventListener('click',()=>showView(btn.dataset.view)));

const fileInput=document.querySelector('#fileInput');const chooseButton=document.querySelector('#chooseButton');const demoButton=document.querySelector('#demoButton');const dropzone=document.querySelector('#dropzone');const uploadPanel=document.querySelector('#uploadPanel');const analysisPanel=document.querySelector('#analysisPanel');const fileName=document.querySelector('#fileName');const fileMeta=document.querySelector('#fileMeta');const progressBar=document.querySelector('#progressBar');const analysisCopy=document.querySelector('#analysisCopy');const checks=[document.querySelector('#check1'),document.querySelector('#check2'),document.querySelector('#check3')];

chooseButton.addEventListener('click',e=>{e.preventDefault();fileInput.click()});fileInput.addEventListener('change',()=>fileInput.files[0]&&startAnalysis(fileInput.files[0]));['dragenter','dragover'].forEach(evt=>dropzone.addEventListener(evt,e=>{e.preventDefault();dropzone.classList.add('drag')}));['dragleave','drop'].forEach(evt=>dropzone.addEventListener(evt,e=>{e.preventDefault();dropzone.classList.remove('drag')}));dropzone.addEventListener('drop',e=>{const file=e.dataTransfer.files[0];if(file)startAnalysis(file)});demoButton.addEventListener('click',()=>startAnalysis({name:'faktura_10652748.pdf',size:420000,type:'application/pdf'}));

function startAnalysis(file){if(file.size>10*1024*1024){alert('Filen är större än 10 MB. Välj en mindre fil.');return}uploadPanel.classList.add('hidden');analysisPanel.classList.remove('hidden');fileName.textContent=file.name||'elrakning.pdf';fileMeta.textContent=`${Math.max(.1,(file.size||150000)/1024/1024).toFixed(1)} MB · lokal MVP-analys`;progressBar.style.width='12%';checks.forEach((c,i)=>c.classList.toggle('active',i===0));analysisCopy.textContent='Identifierar leverantör och avtalsform…';setTimeout(()=>{progressBar.style.width='46%';checks[1].classList.add('active');analysisCopy.textContent='Läser förbrukning, spotpris, påslag och avgifter…'},650);setTimeout(()=>{progressBar.style.width='78%';checks[2].classList.add('active');analysisCopy.textContent='Separera elhandel från elnät och andra kostnader…'},1350);setTimeout(()=>{progressBar.style.width='100%';analysisCopy.textContent='Analysen är klar.'},2050);setTimeout(()=>{analysisPanel.classList.add('hidden');uploadPanel.classList.remove('hidden');showView('electricity')},2450)}

const watchButton=document.querySelector('#watchButton');const watchCard=document.querySelector('#watchCard');const watchStatus=document.querySelector('#watchStatus');const stored=localStorage.getItem('neverOverpayElectricityWatch')==='true';applyWatch(stored);watchButton.addEventListener('click',()=>{const next=localStorage.getItem('neverOverpayElectricityWatch')!=='true';localStorage.setItem('neverOverpayElectricityWatch',String(next));applyWatch(next)});function applyWatch(active){if(active){watchButton.textContent='Bevakning aktiv ✓';watchCard.classList.add('watching');watchStatus.textContent='Aktiv'}else{watchButton.textContent='Bevaka mitt elavtal';watchCard.classList.remove('watching');watchStatus.textContent='Ej aktiverad'}}

// Verified sample extracted from the Tibber July 2026 invoice supplied during MVP testing.
window.NeverOverpayDemoBill=window.NeverOverpayEnergy?.normalizeBill({supplier:'Tibber',invoicePeriod:'2026-07',periodConsumptionKwh:683.44,contractType:'quarter-hourly',energyPriceOrePerKwh:59.29,markupOrePerKwh:6,fixedTradingFeeSekPerMonth:39.2,electricityTradingTotalSek:635,gridCompany:'Vattenfall Eldistribution',taxAndVatSek:126.95,invoiceTotalSek:635,confidence:{supplier:1,periodConsumptionKwh:1,energyPriceOrePerKwh:1,markupOrePerKwh:1,fixedTradingFeeSekPerMonth:1}});